## Restaurant Recommendation System

In [1]:
import pandas as pd
import numpy as np
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
public_ratings_df = pd.read_excel('public opinion.xlsx')
personal_ratings_df = pd.read_excel('My fav.xlsx')

In [3]:
public_ratings_df.head()

Restaurant Name        Type  Ratings   
0                                  Restaurants  Restaurant      5.0  \
1                             Jain Food Nagpur  Restaurant      5.0   
2  Flavours of champaran Mutton & chinese food  Restaurant      5.0   
3                            GREND iSle Restro      Indian      5.0   
4                     Fagito Lounge and Restro  Restaurant      5.0   

                                             Address  
0                        opposite nandanwar hospital  
1                       43XR+M84, Railway Station Rd  
2  8, Gitanjali Housing Society, near by Epicure ...  
3                                           4WRW+5WC  
4                        W High Ct Rd, near SBI Bank

In [4]:
personal_ratings_df.head()

Restaurant Name  Ratings          Type   
0     The Better Butler      3.5          Cafe  \
1    The signature cafe      4.2          Cafe   
2        The momo's Bar      4.0          Cafe   
3  Jai Ambe Chat Corner      2.6  Hawker stall   
4       Temptation café      3.5          Cafe   

                                             Address  
0  322, Ganesh nagar Sharda Square, near Aaradhya...  
1       71, Marwadi Wadi, Shantinagar Colony, Nagpur  
2  New Nandanvan Layout, Ganesh Nagar, Nandanvan,...  
3  SHOP NO. 25,SHRIMAN PALACE, Chandrapur - Nagpu...  
4             491, Nehru Nagar Corner Gurudev square

In [5]:
merged_df = pd.merge(public_ratings_df, personal_ratings_df, on='Restaurant Name')
merged_df.head()

Restaurant Name        Type_x  Ratings_x   
0     The Better Butler          Cafe        4.7  \
1    The signature cafe          Cafe        4.7   
2        The momo's Bar          Cafe        4.6   
3  Jai Ambe Chat Corner  Hawker stall        4.5   
4       Temptation café          Cafe        4.4   

                                           Address_x  Ratings_y        Type_y   
0  322, Ganesh nagar Sharda Square, near Aaradhya...        3.5          Cafe  \
1       71, Marwadi Wadi, Shantinagar Colony, Nagpur        4.2          Cafe   
2  New Nandanvan Layout, Ganesh Nagar, Nandanvan,...        4.0          Cafe   
3  SHOP NO. 25,SHRIMAN PALACE, Chandrapur - Nagpu...        2.6  Hawker stall   
4             491, Nehru Nagar Corner Gurudev square        3.5          Cafe   

                                           Address_y  
0  322, Ganesh nagar Sharda Square, near Aaradhya...  
1       71, Marwadi Wadi, Shantinagar Colony, Nagpur  
2  New Nandanvan Layout, Ganesh Nagar, Nandanvan,...  
3  SHOP NO. 25,SHRIMAN PALACE, Chandrapur - Nagpu...  
4             491, Nehru Nagar Corner Gurudev square

In [38]:
merged_df.duplicated().sum()

0

In [6]:
columns_to_drop = ['Type_y', 'Address_y','Type_x','Address_x']
df = merged_df.drop(columns=columns_to_drop)
df= df.set_index('Restaurant Name')

df

Ratings_x  Ratings_y
Restaurant Name                           
The Better Butler           4.7        3.5
The signature cafe          4.7        4.2
The momo's Bar              4.6        4.0
Jai Ambe Chat Corner        4.5        2.6
Temptation café             4.4        3.5
...                         ...        ...
Roof 9                      3.7        3.3
Cafe Turtle                 3.7        4.2
Aquila Delhi                3.5        4.2
Shivbhojan Thali            3.4        1.5
ICE CREAM PARLOUR           3.3        3.3

[103 rows x 2 columns]

In [7]:
df = df.fillna(0)

In [22]:
#To find similarity score between items
similarity = cosine_similarity(df)
print(similarity)
similarity.shape
 

[[1.         0.99602528 0.99713949 ... 0.97228805 0.97488415 0.98946106]
 [0.99602528 1.         0.99990842 ... 0.98924704 0.95117202 0.99842564]
 [0.99713949 0.99990842 1.         ... 0.98717714 0.95526214 0.9975751 ]
 ...
 [0.97228805 0.98924704 0.98717714 ... 1.         0.8958011  0.99589321]
 [0.97488415 0.95117202 0.95526214 ... 0.8958011  1.         0.93236131]
 [0.98946106 0.99842564 0.9975751  ... 0.99589321 0.93236131 1.        ]]


(103, 103)

In [53]:
#Function which takes a restaurant name as input and returns 5 restaurant recommendations 
def recommend(rest_name):
#fetching index of the restaurant     
    index = np.where(df.index==rest_name)[0][0]
#similarity[index]-->to get (distance)similarity with other restaurants to the index
#enumerate-->to get index along with similarity
#sort-->to get most similar items on top / sort on basis of similarity in ascending order 

    similar_rest = sorted(list(enumerate(similarity[index])),key=lambda x:x[1],reverse=True)[1:6]
    for i in similar_rest:
        print(df.index[i[0]])
    

In [54]:
recommend('Roof 9')

The signature cafe
Galaxy Restra
India Coffee House
Khalsa Dhaba
Brewin Cafe
